# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3882af52cb36c2d418013711c7154dedf2d4ded1a7aa5ee99b06919b8aaa497b4e92fc8f013e1699f6ddb24c0e6c4a63105536d6deb7e858813b6e2dc478b23a

test:
  secret_key_base: a9e520823182e8304a031c1c529d294c6fcd8ac2a66631616d13739e054fe667a99313515ff2e02d7dd7c9ebe1cf16e78ad463c790684dfd9b6ef7be12cd1707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
